<a href="https://colab.research.google.com/github/Atanga-Theresa/Machine-Learning/blob/main/Car_price_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem Statement
Predicting Used Car Prices using Linear Regression

Objective: Develop a linear regression model to predict the selling price of used cars based on key features such as mileage, age, and car brand.

Context: The used car market is influenced by various factors. Understanding how different attributes contribute to a car's selling price is crucial for both buyers and sellers. This assignment aims to build a predictive model that can estimate the price of a used car given its specifications.

Task:

Data Preparation: Load and preprocess a dataset containing used car information. This includes handling categorical variables (e.g., car models) by converting them into a numerical format suitable for regression (e.g., using one-hot encoding).

Model Training: Train a multiple linear regression model using features such as mileage, age, and the encoded car brand.

Prediction & Evaluation: Utilize the trained model to predict the selling prices of hypothetical cars and evaluate the model's performance using an appropriate metric to assess its accuracy in explaining the variance in car prices.

In [1]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.linear_model import LinearRegression
import csv
import warnings
warnings.filterwarnings("ignore")

In [4]:
Car_prices = pd.read_csv("/content/drive/MyDrive/carprices.csv")
Car_prices

Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [7]:
# car models are text instead of numbers. Change to dummies
dummies = pd.get_dummies(Car_prices["Car Model"], drop_first=True)
dummies



BMW X5  Mercedez Benz C class
0     True                  False
1     True                  False
2     True                  False
3     True                  False
4     True                  False
5    False                  False
6    False                  False
7    False                  False
8    False                  False
9    False                   True
10   False                   True
11   False                   True
12   False                   True

In [11]:
# Define features and target
X = pd.concat([Car_prices[["Mileage", "Age(yrs)"]], dummies], axis=1)
y = Car_prices["Sell Price($)"]

In [12]:
# Train model
model=LinearRegression()
model.fit(X,y)

LinearRegression()

In [13]:
# 1) Predict price of a mercedez benz that is 4 yr old with mileage 45000
model.predict([[45000,4,0,0]])

array([34537.77647335])

In [15]:
# 2) Predict price of a BMW X5 that is 7 yr old with mileage 86000
model.predict([[86000,7,0,1]])

array([17818.95045785])

In [16]:
# 3) Tell me the score (accuracy) of your model.
model.score(X,y)

0.9417050937281083

In [17]:
# 4) Predict price of a Audi A5 that is 3 yr old with mileage 30000
model.predict([[30000,3,1,0]])

array([37137.39492839])

In [19]:
# 5) Predict price of a BMW X5 that is 2 yr old with mileage 40000
model.predict([[40000,2,0,1]])

array([41506.83493778])

In [20]:
# 6)Predict the price of a mercedez benz tthat is 1 year old with mileage 20000.
model.predict([[20000,1,0,0]])

array([47788.1897159])

In [21]:
# 7)Predict the price of a mercedez benz t that is 4 years old with mileage 40000
model.predict([[40000,4,0,0]])

array([36388.38694529])